### PR TITLE
Namespace serializers finally (and small base controller bug fix)!

### LINKED ISSUE #533: Namespace serializers
Currently serializers are not namespaced into seperate folders and it's messy.

### LINKED ISSUE #832: Fix authenticate_user filter in client base controller

### PR DESCRIPTION
**Pull request by warrenshen**
Fix #533 
Fix #832

### CODE REVIEW

File: config/application.rb [hunk 1]
```diff
@@ -35,5 +35,8 @@ class Application < Rails::Application
 
     # Do not swallow errors in after_commit/after_rollback callbacks.
     config.active_record.raise_in_transactional_callbacks = true
+
+    # Autoload all serializers within serializers directory
+    config.autoload_paths += Dir[Rails.root.join('app', 'serializers', '**/')]
```
Comment (warrenshen) [inline config/application.rb]: Literally just this line @maxwolffe.
