### PR TITLE
General component and model fixes related to forms

### LINKED ISSUE #1264: Figure out humanization in dropdown options

### PR DESCRIPTION
**Pull request by warrenshen**
Fix #1264

### CODE REVIEW

File: app/models/school_validator.rb [hunk 1]
```diff
@@ -60,7 +60,9 @@ class SchoolValidator
   validates :address_zip, if: :page_one?, presence: true
   validates :name, if: :page_one?, presence: true
 
-  validates :contact_email, if: :page_two?, presence: true
+  validates :contact_email, format: { with: /.+@.+\..+/i },
```
Comment (warrenshen) [inline app/models/school_validator.rb]: This is what a validation for an email looks like @sonia-y .
