### PR TITLE
Create form textarea component along with general form fixes

### LINKED ISSUE #1260: Create form textarea component paralleling form input component

### LINKED ISSUE #1261: Configure textarea as a valid question style

### LINKED ISSUE #1263: School preview not rendering address two or website

### PR DESCRIPTION
**Pull request by warrenshen**
Fix #1260 
Fix #1261
Fix #1263

### CODE REVIEW

File: app/models/school_submission.rb [hunk 1]
```diff
@@ -60,26 +60,36 @@
...
-    :uncle,
-    :grandmother,
-    :grandfather,
-    :stepmother,
-    :stepfather,
-    :guardian,
-  ]
-  enum registration_status: [:registered, :selected, :dropped]
-  enum shirt_size: [:S, :M, :L, :XL, :XXL]
+  enum student_gender: [:female, :male, :other]
```
Comment (warrenshen) [inline app/models/school_submission.rb]: There was an issue where the `student_gender` enum was `gender` instead of `student_gender` - beware of copy pasta errors!

File: app/models/school_submission.rb [hunk 2]
```diff
@@ -60,26 +60,36 @@
...
 
   before_validation :validate_page, on: [:create, :update]
 
+  BOOLEANS = %w(yes no)
+
+  def has_alternate_student
+    if !read_attribute(:has_alternate_student).nil?
+      BOOLEANS[read_attribute(:has_alternate_student)]
+    end
+  end
```
Comment (warrenshen) [inline app/models/school_submission.rb]: These two methods define custom enums for us.

**Comment by sonia-y** [comment]
👍
