### PR TITLE
Fix required/unrequired fields labeling 

### LINKED ISSUE #1472: Question bug: required or not?
screen shot 2016-04-13 at 1 01 43 pm

### LINKED ISSUE #1480: On multiple pages of the student form questions are marked required incorrectly

### PR DESCRIPTION
**Pull request by sonia-y**
Fix #1472 
Fix #1480

### CODE REVIEW

File: app/controllers/api/student_submissions_controller.rb [hunk 1]
```diff
@@ -79,6 +79,8 @@ def student_submission_params
       :guardian_two_phone_number,
       :guardian_two_phone_type,
       :guardian_two_relationship,
+      :health_conditions,
```
Comment (warrenshen) [inline app/controllers/api/student_submissions_controller.rb]: There's already a declaration at the bottom ~ we have to declare `array` type params after everything else.

File: app/models/student_validator.rb [hunk 2]
```diff
@@ -163,7 +154,6 @@ class StudentValidator
   validates :media_participation, if: :page_six?, presence: true
 
   validates :ceremony_attendance, if: :page_seven?, presence: true
-  validates :ceremony_attendance_number, if: :parent_attending?, presence: true
```
Comment (warrenshen) [inline app/models/student_validator.rb]: Ooh this isn't required?

File: db/seeds/development/forms_seed.rb [hunk 3]
```diff
@@ -664,6 +670,15 @@
       ),
     )
     Question.create(
+      is_required: false,
+      key: 'health_conditions_description',
+      page: page,
+      style: Question.styles[:textarea],
+      title: %s(
```
Comment (warrenshen) [inline db/seeds/development/forms_seed.rb]: We don't need to use `%s` here this it's short!

File: db/seeds/development/forms_seed.rb [hunk 4]
```diff
@@ -1245,7 +1262,14 @@
...
-    description: %s(
+    description: 'Particpation Description',
+    form: form,
+    is_last: true,
+    number: 9,
+    title: 'Participation Commitment',
+  ) do |page|
+    Question.create(
+      description: %s(
       Dear Participant, <br />
```
Comment (warrenshen) [inline db/seeds/development/forms_seed.rb]: Tab these lines in by 2 (run `rubocop` and see what it says).

File: db/seeds/development/submissions_seed.rb [hunk 5]
```diff
@@ -93,6 +93,7 @@
   guardian_two_phone_type: EnumConstants::PHONE_TYPES.sample,
   guardian_two_relationship: EnumConstants::GUARDIAN_RELATIONSHIPS.sample,
   health_conditions: EnumConstants::HEALTH_CONDITIONS.sample,
+  health_conditions_description: Faker::Name.first_name,
```
Comment (warrenshen) [inline db/seeds/development/submissions_seed.rb]: For this one and others similar, instead of `first_name` seed we can just do `'None'`.

File: spec/factories/students.rb [hunk 6]
```diff
@@ -87,6 +88,7 @@
     guardian_two_phone_type    { EnumConstants::PHONE_TYPES.sample }
     guardian_two_relationship  { EnumConstants::GUARDIAN_RELATIONSHIPS.sample }
     health_conditions          { EnumConstants::BOOLEANS.sample }
+    health_conditions_other    { 'NONE' }
```
Comment (warrenshen) [inline spec/factories/students.rb]: `None`.

Comment (warrenshen) [inline spec/factories/students.rb]: As well, none of the model annotations had a field `health_conditions_other` - did you forget to run `annotate` after creating that field?

File: db/seeds/development/forms_seed.rb [hunk 7]
```diff
@@ -576,39 +576,45 @@
...
     )
     Question.create(
+      is_required: false,
       key: 'guardian_two_last_name',
       page: page,
       style: Question.styles[:input],
       title: 'Parent/Guardian 2 Last Name',
     )
     Question.create(
+      is_required: false,
```
Comment (warrenshen) [inline db/seeds/development/forms_seed.rb]: Alphabetize!

File: db/seeds/development/forms_seed.rb [hunk 8]
```diff
@@ -576,39 +576,45 @@
...
       description: StringConstants::EMAIL_FORMAT,
       key: 'guardian_two_email',
       page: page,
       style: Question.styles[:input],
       title: 'Parent/Guardian 2 Email',
     )
     Question.create(
+      is_required: false,
```
Comment (warrenshen) [inline db/seeds/development/forms_seed.rb]: Alphabetize!

File: db/seeds/development/forms_seed.rb [hunk 9]
```diff
@@ -1111,6 +1127,7 @@
       title: 'Will you join us on Sunday?',
     )
     Question.create(
+      is_required: false,
```
Comment (warrenshen) [inline db/seeds/development/forms_seed.rb]: Alphabetize!

**Comment by warrenshen** [comment]
@sonia-y commented! Run `bundle exec rspec` to see why the build is failing as well.
