### PR TITLE
Important form fixes: save any correct data regardless of presence of errors and allow client to always navigate to previous page when wanted

### LINKED ISSUE #1200: Should allow client to go to previous page (but still save partial data)

### LINKED ISSUE #1346: Save valid data of form input even with some errors

### PR DESCRIPTION
**Pull request by warrenshen**
Fix #1200 
Fix #1346 

@sonia-y !!!

### CODE REVIEW

File: app/models/school_validator.rb [hunk 1]
```diff
@@ -8,11 +8,13 @@ class SchoolValidator
   attr_accessor :address_city,
                 :address_one,
                 :address_state,
+                :address_two,
```
Comment (warrenshen) [inline app/models/school_validator.rb]: We need to include `attr_accessor` even for optional params now - although we still won't do any validations on them in the `...Validator` class.

File: app/models/school_validator.rb [hunk 2]
```diff
@@ -133,8 +140,7 @@ class SchoolValidator
   validates :alternate_last_name, if: :has_alternate?, presence: true
   validates :alternate_shirt_size, if: :has_alternate?, presence: true
 
-  def initialize(attributes={}, page=0)
-    @page = page
+  def initialize(attributes={})
```
Comment (warrenshen) [inline app/models/school_validator.rb]: Since we pass in `current_page` with the `update_params`, we don't need to store it!

File: app/models/student_submission.rb [hunk 3]
```diff
@@ -168,6 +167,29 @@ def full_name
     "#{first_name} #{last_name}"
   end
 
+  def custom_update(update_params)
```
Comment (warrenshen) [inline app/models/student_submission.rb]: Same logic as in `SchoolSubmission`.

File: app/models/school_submission.rb [hunk 4]
```diff
@@ -60,8 +60,6 @@
 
 class SchoolSubmission < ActiveRecord::Base
 
-  before_validation :validate_page, on: [:create, :update]
```
Comment (warrenshen) [inline app/models/school_submission.rb]: Since we aren't depending on lifecycle methods (instead we call our own method), we don't need these anymore!
