### PR TITLE
Student comment bug fixes

### LINKED ISSUE #407: Set up comment create to close overlay after successful create

### LINKED ISSUE #408: Fix Student Comment Create
After refresh, comment made does not show up (it shows up on make though)

### PR DESCRIPTION
**Pull request by maxwolffe**
Fix #407 
Fix #408

### CODE REVIEW

File: app/controllers/api/students/comments_controller.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@ class Api::Students::CommentsController < Api::BaseController
 
   def create
     comment = Comment.new comment_params
+    comment.student_id = params[:student_id]
```
Comment (warrenshen) [inline app/controllers/api/students/comments_controller.rb]: Can you do me a favor and just try `comment.student = params[:student_id]`? I have a feeling the convention is that this magic should work.

**Comment by warrenshen** [comment]
I think we'll refactor the `StudentComments...` alt stuff into the `Student...` alt stuff later!

File: app/controllers/api/students/comments_controller.rb (hunk 1 above)
Comment (warrenshen) [inline app/controllers/api/students/comments_controller.rb]: I was wrong!
