### PR TITLE
Fix serializers with stable version of active_model_serializers

### LINKED ISSUE #545: Create form, section, and question serializer

### LINKED ISSUE #546: Downgrade active_model_serializers to stable release

### LINKED ISSUE #547: Refactor out unnecessary comments request from student page

### LINKED ISSUE #548: Fix all serializers based on new active_model_serializers version

### PR DESCRIPTION
**Pull request by warrenshen**
Merge after #549.

Fix #545 
Fix #546 
Fix #547 
Fix #548

### CODE REVIEW

File: app/controllers/api/students_controller.rb [hunk 1]
```diff
@@ -10,20 +10,20 @@ def create
   end
 
   def index
-    students = Student.includes(:school).page params[:page]
+    students = Student.includes(:group, :school).page params[:page]
```
Comment (warrenshen) [inline app/controllers/api/students_controller.rb]: `.includes` tells the query to also grab related `group` and `school` when grabbing a `student` record. This saves us queries when the serializers try to follow their respective `has_one`s.

File: app/controllers/api/students_controller.rb [hunk 2]
```diff
@@ -10,20 +10,20 @@ def create
...
     render json: students,
                  serializer: PaginatedSerializer,
                  each_serializer: StudentIndexSerializer
   end
 
   def show
-    student = Student.find params[:id]
+    student = Student.includes(comments: :user).find params[:id]
```
Comment (warrenshen) [inline app/controllers/api/students_controller.rb]: This `.includes(comments: :user)` includes associated `comments` and then associated `user` of each comment.

**Comment by maxwolffe** [comment]
Cool. LGTM!
